name: continious integration
on: push
jobs:
  build_server:
    name: build server
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go build server
        run: |
          cd server/src
          go build .
      - name: upload binary
        uses: actions/upload-artifact@v2
        with:
          name: server-binary
          path: server/src/server


  build_client:
    name: build client
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go build client
        run: |
          cd client/src
          go build .
      - name: upload binary
        uses: actions/upload-artifact@v2
        with:
          name: client_binary
          path: client/src/client


  test_server:
    needs: build_server
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go test
        run: |
          cd server/src/
          go test .

  test_client:
    name: test client
    needs: build_client
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go test
        run: |
          cd client/src
          go test .


