name: continious integration
on: push
jobs:
  build_server:
    name: build server
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go build server
        run: go build .
        working-directory: ./server/src
      - name: upload binary
        uses: actions/upload-artifact@v2
        with:
          name: server_binary
          path: server/src/server


  build_client:
    name: build client
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go build client
        run: go build .
        working-directory: ./client
      - name: upload binary
        uses: actions/upload-artifact@v2
        with:
          name: client_binary
          path: client/client


  test_server:
    name: test server
    needs: build_server
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go test
        run: go test .
        working-directory: ./server/src

  test_client:
    name: test client
    needs: [build_client, build_server, test_server]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get go build artifact
        uses: actions/download-artifact@v2
        with:
          name: server_binary
          path: server_bin
      - name: go test
        run: ../server_bin/server & go test .
        working-directory: ./client


